### ISSUE TITLE
Dependency issue 

### ISSUE THREAD

**Issue by takenalias** [Azure/iotc-device-bridge#62]
Hi, I am getting the following error on a new install. 

2020-11-24T02:57:11.580 [Error] Executed 'Functions.IoTCIntegration' (Failed, Id=76058f0f-d3b6-4006-b5b6-bc1f194ada86, Duration=3ms)Result: FailureException: Worker was unable to load function IoTCIntegration: 'Error: Cannot find module 'node-fetch''Stack: Error: Cannot find module 'node-fetch'at Function.Module._resolveFilename (module.js:548:15)at Function.Module._load (module.js:475:25)at Module.require (module.js:597:17)at require (internal/module.js:11:18)at Object.<anonymous> (C:\home\site\wwwroot\IoTCIntegration\index.js:6:15)at Module._compile (module.js:653:30)at Object.Module._extensions..js (module.js:664:10)at Module.load (module.js:566:32)at tryModuleLoad (module.js:506:12)at Function.Module._load (module.js:498:3)

the node-fetch module is indeed in the modules folder.

**Comment by takenalias** [comment]
I had to run npm ci to fix this.

**Comment by sandervandevelde** [comment]
This seems to help in the right folder:

![image](https://user-images.githubusercontent.com/694737/142224232-b8c4f00c-2edd-4c74-8d3d-ed912d9d402d.png)
